//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class RegisterDetail
    {
        [Required]
        [Display(Name = "Register Id")]
        public int R_Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        [RegularExpression("[A-za-z]*", ErrorMessage = "Name should contain alphabets only!")]
        public string R_Name { get; set; }

        [Required]
        [RegularExpression("[A-za-z]*", ErrorMessage = "User name should contain alphabets only!")]
        [Display(Name = "UserName")]
        [Remote("IsUserNameExits", "RegisterCustomer", ErrorMessage = "User name already exits")]
        public string R_Username { get; set; }


        [Required]
        [Display(Name = "Address")]
        public string R_Address { get; set; }


        [Required]
        [MaxLength(8, ErrorMessage = "Maximum Length should be 8")]
        [MinLength(3, ErrorMessage = "Minimum Length should be 3")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string R_Password { get; set; }

        [Required]
        [RegularExpression("[A-za-z]*", ErrorMessage = "Role can be Customer!")]
        [Display(Name = "Role")]
        public string R_Role { get; set; }
    }
}
